export const describeImagePrompt =
  "A visual representation of the year illustrating the transformative global impact of the beef industry coming to a halt due to its significant contribution to climate change and carbon emissions, The first image should start in 2019, showing a world heavily reliant on beef with visible signs of environmental degradation such as deforestation and high carbon emissions. As the timeline advances, depict the transition towards more sustainable practices with the emergence of expansive fish farms in the oceans of Norway by 2025, which become a major global source of protein. Illustrate the revitalization of marine ecosystems and cleaner air resulting from reduced beef production. By 2035, show how cities have adapted to new dietary and economic realities, with markets and restaurants prominently featuring fish-based dishes. Conclude the series of images in 2044 with a vision of a sustainable future where fish farming is fully integrated into society, helping restore terrestrial ecosystems previously dedicated to cattle grazing. This visual narrative should effectively showcase a world undergoing significant ecological and societal changes due to the shift from beef to fish protein. We must see an advancement of cleaner more sustainable world as the images proceed. Every second image should show an advancement in cleaner solutions .As the timeline advances, the focus shifts to the emergence of large-scale fish vessels situated in oceans worldwide. These vessels, resembling huge circular boats, are equipped with advanced technology including sensors, monitors, and control units. They provide completely autonomous feeding and monitoring of fish. The vessels feature a rotating self-cleaning gate that ensures the cleanliness of the farm netting, eliminating biofouling that can harm the fish. High monitoring and onboard laboratories mitigate the risk of sea lice, ensuring optimal fish health. The vessels also process the fish onboard for trading, eliminating the need for on-land procedures or storage. These vessels span an impressive 14 kilometers, showcasing the scale of this innovative approach to protein production.";

export const generateTagsPrompt =
  "The user will provide you with a description of something that needs to be tagged. Generate a set of comma separated nouns, verbs and adjectives that suggest possible tags. Only generate comma separated words with no other text or explanation.";

export const generateCoordinatesPrompt = `The user will provide you with a description of a map that they would like you to generate.
  Generate a JSON object containing an array of coordinates describing locations on the map using the following format:
  {map:[{description:string, coordinates:{x:number, y:number}]}
  X and Y coordinates should be floating point values between 0 and 100
  Only return the JSON object with no other text or explanation.
  `;
